// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3395iRHhTDgArQKyTF13maddQsr8AdIY',
    appId: '1:779253461806:web:024b27aa634549dbf3c0bf',
    messagingSenderId: '779253461806',
    projectId: 'vs6451071091-2d0ff',
    authDomain: 'vs6451071091-2d0ff.firebaseapp.com',
    storageBucket: 'vs6451071091-2d0ff.firebasestorage.app',
    measurementId: 'G-D923M5D1JT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6V2qSoIT8ZqD-j1a3klmu0ZJgQveRyic',
    appId: '1:779253461806:android:d45de905e58ac7e9f3c0bf',
    messagingSenderId: '779253461806',
    projectId: 'vs6451071091-2d0ff',
    storageBucket: 'vs6451071091-2d0ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAauWhFA0EQpdqExecxX-scejDyk6Q591s',
    appId: '1:779253461806:ios:c414defcf8cbb6e7f3c0bf',
    messagingSenderId: '779253461806',
    projectId: 'vs6451071091-2d0ff',
    storageBucket: 'vs6451071091-2d0ff.firebasestorage.app',
    iosClientId: '779253461806-u6ok6q9htb5dcjesonot2tb8tcratsf2.apps.googleusercontent.com',
    iosBundleId: 'com.example.manageFlowerStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAauWhFA0EQpdqExecxX-scejDyk6Q591s',
    appId: '1:779253461806:ios:c414defcf8cbb6e7f3c0bf',
    messagingSenderId: '779253461806',
    projectId: 'vs6451071091-2d0ff',
    storageBucket: 'vs6451071091-2d0ff.firebasestorage.app',
    iosClientId: '779253461806-u6ok6q9htb5dcjesonot2tb8tcratsf2.apps.googleusercontent.com',
    iosBundleId: 'com.example.manageFlowerStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3395iRHhTDgArQKyTF13maddQsr8AdIY',
    appId: '1:779253461806:web:37b51e3864db74caf3c0bf',
    messagingSenderId: '779253461806',
    projectId: 'vs6451071091-2d0ff',
    authDomain: 'vs6451071091-2d0ff.firebaseapp.com',
    storageBucket: 'vs6451071091-2d0ff.firebasestorage.app',
    measurementId: 'G-8FMBE3PYVE',
  );
}
